server:
  port: 9092

spring:
  application:
    name: msvc-movimientoscuenta
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/movimientosDb
    username: root
    password: my-weak-password
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka