server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clientes
          uri: http://localhost:9091
          predicates:
            - Path=/api/clientes/**
        - id: cuentas
          uri: http://localhost:9092
          predicates:
            - Path=/api/cuentas/**
        - id: movimientos
          uri: http://localhost:9092
          predicates:
            - Path=/api/movimientos/**

eureka:
  client:
    register-with-eureka: false