server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: msvc-eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    serverUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    ebable-self-preservation: false